### ISSUE TITLE
Please disregard

### ISSUE THREAD

**Issue by keriwarr** [josephfrazier/standard-eject#2]
- [ ] Use `yarn` ?

**Comment by josephfrazier** [comment]
Can you elaborate? standard-eject already [detects and uses yarn](https://github.com/josephfrazier/standard-eject/blob/b5f79f1eaa87c54cc9425a1637ad55b3d2ccf98d/bin/standard-eject#L32-L39), and the project itself also uses yarn.lock to keep track of its own dependencies.

**Comment by keriwarr** [comment]
ahh, I'm sorry. I opened this on the wrong repo
